FROM node:lts-alpine
# FROM node:13.12.0-alpine
WORKDIR "/app"
COPY ./package.json ./
# RUN npm cache clear --force
RUN npm install --verbose
COPY . .
CMD ["npm", "run", "start"]

# FROM node:16-alpine
 
# USER node
 
# RUN mkdir -p /home/node/app
# WORKDIR /home/node/app
 
# COPY --chown=node:node ./package.json ./
# RUN npm install
# COPY --chown=node:node ./ ./
 
# CMD ["npm", "start", "run"]
