name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: '${{ secrets.DOCKER_PASSWORD }}'
      
      - run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t rallycoding/multi-client ./client
      - run: docker build -t rallycoding/multi-nginx ./nginx
      - run: docker build -t rallycoding/multi-server ./server
      - run: docker build -t rallycoding/multi-worker ./worker

      - run: docker push rallycoding/multi-client
      - run: docker push rallycoding/multi-nginx
      - run: docker push rallycoding/multi-server
      - run: docker push rallycoding/multi-worker
      